### PR TITLE
Prep 1.2.1 Release to Master

### PR DESCRIPTION
**Pull request by jpcunningh**
Major updates include:
* Support for G6
* Support for transmitter back fill
* Refactor to ES6 with airbnb style

### CODE REVIEW

**Comment by efidoman** [comment]
LGTM. Has someone run this version successfully with Logger and/or Lookout ahead of merge to Master?

**Comment by jpcunningh** [comment]
I've been running it with Lookout for about a week.

**Comment by jpcunningh** [comment]
Has anyone had a chance to test this with Logger?

**Comment by efidoman** [comment]
Setup worked flawlessly. Logger working perfectly so far including a calibration I just completed. I suggest I run it for at least a day and make sure everything continues to work.

**Comment by efidoman** [comment]
All good. No issues. Ready to go in my opinion.

**Comment by jpcunningh** [comment]
Great! Thank you!

**Pull request merged**
